### PR TITLE
Revert 7e935e92 for kernel < 6

### PR DESCRIPTION
**Pull request by g-chauvel**
On Ubuntu 22.04 LTS, the following error is caused by 7e935e92 
```
/virtual/main.c:72:28: error: use of undeclared identifier 'ITER_UBUF'
    if (iter->iter_type == ITER_UBUF) {
                           ^
/virtual/main.c:75:21: error: no member named 'ubuf' in 'struct iov_iter'
        buf = iter->ubuf;
              ~~~~  ^
2 errors generated.
Traceback (most recent call last):
  File "/root/sockdump/./sockdump.py", line 386, in <module>
    main(args)
  File "/root/sockdump/./sockdump.py", line 327, in main
    b = BPF(text=text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 479, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

### CODE REVIEW

**Comment by mechpen** [comment]
thanks for the fix!
