### ISSUE TITLE
Compilation error: cannot take the address of an rvalue of type 'typeof(struct iov_iter)'

### ISSUE THREAD

**Issue by chrahunt** [mechpen/sockdump#1]
OS: Linux
Distribution: Ubuntu 18.04
Kernel version: 4.15.0-48-generic

1. Executed `sudo apt install bpfcc-tools python3-bpfcc`.
2. Cloned this repository.
3. Executed

```  
/usr/bin/python3 sockdump.py /proc/28937/cwd/socket --format pcap --output dump
```

which output:

```
/virtual/main.c:54:12: error: cannot take the address of an rvalue of type 'typeof(struct iov_iter)'
      (aka 'struct iov_iter')
  ...&({ typeof(struct iov_iter) _val; memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&msg->msg_iter); _val; });
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "sockdump.py", line 303, in <module>
    main(args)
  File "sockdump.py", line 252, in main
    b = BPF(text=text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 301, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module
```

**Comment by chrahunt** [comment]
The error is silenced if [this line](https://github.com/mechpen/sockdump/blob/master/sockdump.py#L70) is replaced with

```
iter = (struct iov_iter *) (msg + offsetof(struct msghdr, msg_iter));
```

but that's not necessarily a good thing.

**Comment by chrahunt** [comment]
Using the latest stable instead of what was in multiverse did the trick. Platform-specific instructions for download or building are [here](https://github.com/iovisor/bcc/blob/master/INSTALL.md). It works with 0.9.0 as of this writing.
